"""M1: 事实表/进度/计划/版本/记忆/审计 全量建表

建出 v6 §6.1 列举的全部 PG 表，共 27 张：

- 版本：data_snapshots / rulesets / semantics_versions
- 事实：persons / person_aircraft_types / person_qualifications /
  person_unavailability / person_completed_missions / aircraft /
  aircraft_mission_capability / aircraft_maintenance / airspaces / missions /
  mission_aircraft_types / mission_prereq / runways / runway_aircraft_types
- 进度：training_progress（字段严格照 v6 §6.3，含 S-11 的 is_recurrent /
  recurrent_since）
- 计划：plans / sorties / sortie_crew / training_debts / blocked_items
- 记忆：episodic_memories / procedural_memories（含 valid_from / valid_to /
  superseded_by）
- 审计：audit_log / trace_events

LangGraph 的 checkpoint 表不在本迁移内 —— 它们由 `PostgresSaver` 自带的内部
迁移负责，见下一个 revision。

**值域刻意放宽，不把基准数据当系统上限**：编号只固定前缀约定不限位数
（`^P[0-9]+$` / `^AC[0-9]+$` / `^mission[A-Z]-[0-9]+$` / `^RWY-[0-9]+$`），
机型不设 CHECK（由上传的飞机资源文件决定），课目类别放宽到 `^[A-Z]$`。
仍设枚举 CHECK 的只有 `identity` 与 `level` —— 它们驱动 §3.1.1 的机组编成
判定式，新增取值意味着新的编成规则，必须先有业务方裁决。

**回滚**：`downgrade()` 按外键依赖反序 drop 全部 27 张表，已实测
`upgrade → downgrade → upgrade` 往返干净。

Revision ID: 4650109da8d3
Revises:
Create Date: 2026-08-10
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "4650109da8d3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("audit_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("audit_id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "ix_audit_log_resource", "audit_log", ["resource_type", "resource_id"], unique=False
    )
    op.create_index(op.f("ix_audit_log_ts"), "audit_log", ["ts"], unique=False)
    op.create_table(
        "data_snapshots",
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("normalized_facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("confirmed_by", sa.String(length=64), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('PENDING', 'ACTIVE', 'SUPERSEDED', 'REJECTED')",
            name=op.f("ck_data_snapshots_snapshot_status_enum"),
        ),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_data_snapshots")),
    )
    op.create_table(
        "episodic_memories",
        sa.Column("memory_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_by", sa.String(length=64), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("chroma_doc_id", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from",
            name=op.f("ck_episodic_memories_episodic_validity_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["episodic_memories.memory_id"],
            name=op.f("fk_episodic_memories_superseded_by_episodic_memories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("memory_id", name=op.f("pk_episodic_memories")),
    )
    op.create_index(
        op.f("ix_episodic_memories_session_id"), "episodic_memories", ["session_id"], unique=False
    )
    op.create_index(
        "ix_episodic_memories_validity",
        "episodic_memories",
        ["valid_from", "valid_to"],
        unique=False,
    )
    op.create_table(
        "procedural_memories",
        sa.Column("memory_id", sa.String(length=64), nullable=False),
        sa.Column("namespace", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_by", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from",
            name=op.f("ck_procedural_memories_procedural_validity_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["procedural_memories.memory_id"],
            name=op.f("fk_procedural_memories_superseded_by_procedural_memories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("memory_id", name=op.f("pk_procedural_memories")),
        sa.UniqueConstraint(
            "namespace", "key", "valid_from", name="uq_procedural_memories_namespace_key_valid_from"
        ),
    )
    op.create_index(
        "ix_procedural_memories_lookup",
        "procedural_memories",
        ["namespace", "key", "valid_from"],
        unique=False,
    )
    op.create_table(
        "rulesets",
        sa.Column("ruleset_version", sa.String(length=32), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("rule_count", sa.Integer(), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "loaded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("ruleset_version", name=op.f("pk_rulesets")),
    )
    op.create_table(
        "semantics_versions",
        sa.Column("semantics_version", sa.String(length=32), nullable=False),
        sa.Column("decided_on", sa.Date(), nullable=False),
        sa.Column("decided_by", sa.String(length=64), nullable=False),
        sa.Column("switches", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "loaded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("semantics_version", name=op.f("pk_semantics_versions")),
    )
    op.create_table(
        "trace_events",
        sa.Column("event_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("agent", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("token_usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0",
            name=op.f("ck_trace_events_trace_duration_nonneg"),
        ),
        sa.CheckConstraint("seq >= 0", name=op.f("ck_trace_events_trace_seq_nonneg")),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_trace_events")),
        sa.UniqueConstraint("run_id", "seq", name="uq_trace_events_run_id_seq"),
    )
    op.create_index(op.f("ix_trace_events_run_id"), "trace_events", ["run_id"], unique=False)
    op.create_table(
        "aircraft",
        sa.Column("aircraft_id", sa.String(length=8), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("aircraft_type", sa.String(length=8), nullable=False),
        sa.Column("seats", sa.Integer(), nullable=False),
        sa.Column("daily_window_start", sa.Time(), nullable=False),
        sa.Column("daily_window_end", sa.Time(), nullable=False),
        sa.Column("turnaround_minutes", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "aircraft_id ~ '^AC[0-9]+$'", name=op.f("ck_aircraft_aircraft_id_format")
        ),
        sa.CheckConstraint(
            "daily_window_start < daily_window_end",
            name=op.f("ck_aircraft_aircraft_window_ordered"),
        ),
        sa.CheckConstraint("seats > 0", name=op.f("ck_aircraft_aircraft_seats_positive")),
        sa.CheckConstraint(
            "turnaround_minutes >= 0", name=op.f("ck_aircraft_aircraft_turnaround_nonneg")
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["data_snapshots.snapshot_id"],
            name=op.f("fk_aircraft_snapshot_id_data_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("aircraft_id", "snapshot_id", name=op.f("pk_aircraft")),
    )
    op.create_table(
        "airspaces",
        sa.Column("airspace_id", sa.String(length=16), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.CheckConstraint("capacity >= 1", name=op.f("ck_airspaces_airspace_capacity_positive")),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["data_snapshots.snapshot_id"],
            name=op.f("fk_airspaces_snapshot_id_data_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("airspace_id", "snapshot_id", name=op.f("pk_airspaces")),
    )
    op.create_table(
        "persons",
        sa.Column("person_id", sa.String(length=8), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("identity", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "identity IN ('教员', '成熟飞行员', '学员')",
            name=op.f("ck_persons_person_identity_enum"),
        ),
        sa.CheckConstraint("person_id ~ '^P[0-9]+$'", name=op.f("ck_persons_person_id_format")),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["data_snapshots.snapshot_id"],
            name=op.f("fk_persons_snapshot_id_data_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("person_id", "snapshot_id", name=op.f("pk_persons")),
    )
    op.create_table(
        "plans",
        sa.Column("plan_id", sa.String(length=64), nullable=False),
        sa.Column("iso_week", sa.String(length=8), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("week_end", sa.Date(), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("ruleset_version", sa.String(length=32), nullable=False),
        sa.Column("semantics_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("relax_tier", sa.Integer(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("solver_stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_by", sa.String(length=64), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('OPTIMAL', 'FEASIBLE', 'INFEASIBLE', 'UNKNOWN', 'MODEL_INVALID')",
            name=op.f("ck_plans_plan_status_enum"),
        ),
        sa.CheckConstraint(
            "relax_tier BETWEEN 0 AND 3", name=op.f("ck_plans_plan_relax_tier_range")
        ),
        sa.CheckConstraint("week_start <= week_end", name=op.f("ck_plans_plan_week_ordered")),
        sa.ForeignKeyConstraint(
            ["ruleset_version"],
            ["rulesets.ruleset_version"],
            name=op.f("fk_plans_ruleset_version_rulesets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["semantics_version"],
            ["semantics_versions.semantics_version"],
            name=op.f("fk_plans_semantics_version_semantics_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["data_snapshots.snapshot_id"],
            name=op.f("fk_plans_snapshot_id_data_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("plan_id", name=op.f("pk_plans")),
        sa.UniqueConstraint("iso_week", "plan_version", name="uq_plans_iso_week_plan_version"),
    )
    op.create_table(
        "runways",
        sa.Column("runway_id", sa.String(length=8), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.CheckConstraint("runway_id ~ '^RWY-[0-9]+$'", name=op.f("ck_runways_runway_id_format")),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["data_snapshots.snapshot_id"],
            name=op.f("fk_runways_snapshot_id_data_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("runway_id", "snapshot_id", name=op.f("pk_runways")),
    )
    op.create_table(
        "aircraft_maintenance",
        sa.Column("aircraft_id", sa.String(length=8), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("start_ts", sa.DateTime(), nullable=False),
        sa.Column("end_ts", sa.DateTime(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("all_day", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "start_ts < end_ts", name=op.f("ck_aircraft_maintenance_maintenance_interval_ordered")
        ),
        sa.ForeignKeyConstraint(
            ["aircraft_id", "snapshot_id"],
            ["aircraft.aircraft_id", "aircraft.snapshot_id"],
            name=op.f("fk_aircraft_maintenance_aircraft_id_snapshot_id_aircraft"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "aircraft_id", "snapshot_id", "start_ts", name=op.f("pk_aircraft_maintenance")
        ),
    )
    op.create_table(
        "blocked_items",
        sa.Column("blocked_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plan_id", sa.String(length=64), nullable=False),
        sa.Column("person_id", sa.String(length=8), nullable=False),
        sa.Column("mission_id", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("missing_prereqs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.plan_id"],
            name=op.f("fk_blocked_items_plan_id_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("blocked_id", name=op.f("pk_blocked_items")),
        sa.UniqueConstraint("plan_id", "person_id", "mission_id", name="uq_blocked_items_key"),
    )
    op.create_index(op.f("ix_blocked_items_plan_id"), "blocked_items", ["plan_id"], unique=False)
    op.create_table(
        "missions",
        sa.Column("mission_id", sa.String(length=16), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("mission_class", sa.String(length=2), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("cycle_weeks", sa.Integer(), nullable=False),
        sa.Column("freq_days", sa.Integer(), nullable=False),
        sa.Column("weekly_required", sa.Boolean(), nullable=False),
        sa.Column("dual_required", sa.Boolean(), nullable=False),
        sa.Column("airspace_id", sa.String(length=16), nullable=False),
        sa.Column("frequency_text", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "mission_class ~ '^[A-Z]$'", name=op.f("ck_missions_mission_class_format")
        ),
        sa.CheckConstraint(
            "mission_id ~ '^mission[A-Z]-[0-9]+$'", name=op.f("ck_missions_mission_id_format")
        ),
        sa.CheckConstraint(
            "cycle_weeks > 0", name=op.f("ck_missions_mission_cycle_weeks_positive")
        ),
        sa.CheckConstraint(
            "duration_minutes > 0", name=op.f("ck_missions_mission_duration_positive")
        ),
        sa.CheckConstraint("freq_days > 0", name=op.f("ck_missions_mission_freq_days_positive")),
        sa.ForeignKeyConstraint(
            ["airspace_id", "snapshot_id"],
            ["airspaces.airspace_id", "airspaces.snapshot_id"],
            name=op.f("fk_missions_airspace_id_snapshot_id_airspaces"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["data_snapshots.snapshot_id"],
            name=op.f("fk_missions_snapshot_id_data_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("mission_id", "snapshot_id", name=op.f("pk_missions")),
    )
    op.create_table(
        "person_aircraft_types",
        sa.Column("person_id", sa.String(length=8), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("aircraft_type", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id", "snapshot_id"],
            ["persons.person_id", "persons.snapshot_id"],
            name=op.f("fk_person_aircraft_types_person_id_snapshot_id_persons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "person_id", "snapshot_id", "aircraft_type", name=op.f("pk_person_aircraft_types")
        ),
    )
    op.create_table(
        "person_qualifications",
        sa.Column("person_id", sa.String(length=8), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("mission_class", sa.String(length=2), nullable=False),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "level IN ('教员', '单飞', '带飞')",
            name=op.f("ck_person_qualifications_qualification_level_enum"),
        ),
        sa.CheckConstraint(
            "mission_class ~ '^[A-Z]$'",
            name=op.f("ck_person_qualifications_qualification_class_format"),
        ),
        sa.ForeignKeyConstraint(
            ["person_id", "snapshot_id"],
            ["persons.person_id", "persons.snapshot_id"],
            name=op.f("fk_person_qualifications_person_id_snapshot_id_persons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "person_id", "snapshot_id", "mission_class", name=op.f("pk_person_qualifications")
        ),
    )
    op.create_table(
        "person_unavailability",
        sa.Column("person_id", sa.String(length=8), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("unavailable_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id", "snapshot_id"],
            ["persons.person_id", "persons.snapshot_id"],
            name=op.f("fk_person_unavailability_person_id_snapshot_id_persons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "person_id", "snapshot_id", "unavailable_date", name=op.f("pk_person_unavailability")
        ),
    )
    op.create_table(
        "runway_aircraft_types",
        sa.Column("runway_id", sa.String(length=8), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("aircraft_type", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["runway_id", "snapshot_id"],
            ["runways.runway_id", "runways.snapshot_id"],
            name=op.f("fk_runway_aircraft_types_runway_id_snapshot_id_runways"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "runway_id", "snapshot_id", "aircraft_type", name=op.f("pk_runway_aircraft_types")
        ),
    )
    op.create_table(
        "sorties",
        sa.Column("sortie_id", sa.String(length=32), nullable=False),
        sa.Column("plan_id", sa.String(length=64), nullable=False),
        sa.Column("flight_date", sa.Date(), nullable=False),
        sa.Column("weekday", sa.String(length=4), nullable=False),
        sa.Column("takeoff", sa.Time(), nullable=False),
        sa.Column("landing", sa.Time(), nullable=False),
        sa.Column("mission_id", sa.String(length=16), nullable=False),
        sa.Column("mission_name", sa.String(length=32), nullable=False),
        sa.Column("airspace_id", sa.String(length=8), nullable=False),
        sa.Column("aircraft_id", sa.String(length=8), nullable=False),
        sa.Column("runway_id", sa.String(length=8), nullable=False),
        sa.Column("is_recurrent", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "runway_id IN ('RWY-1', 'RWY-2')", name=op.f("ck_sorties_sortie_runway_enum")
        ),
        sa.CheckConstraint(
            "weekday IN ('周一', '周二', '周三', '周四', '周五', '周六', '周日')",
            name=op.f("ck_sorties_sortie_weekday_enum"),
        ),
        sa.CheckConstraint("takeoff < landing", name=op.f("ck_sorties_sortie_time_ordered")),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.plan_id"],
            name=op.f("fk_sorties_plan_id_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("sortie_id", name=op.f("pk_sorties")),
        sa.UniqueConstraint(
            "plan_id", "aircraft_id", "flight_date", "takeoff", name="uq_sorties_aircraft_slot"
        ),
    )
    op.create_index(op.f("ix_sorties_plan_id"), "sorties", ["plan_id"], unique=False)
    op.create_table(
        "training_debts",
        sa.Column("debt_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plan_id", sa.String(length=64), nullable=False),
        sa.Column("person_id", sa.String(length=8), nullable=False),
        sa.Column("mission_id", sa.String(length=16), nullable=False),
        sa.Column("required_count", sa.Integer(), nullable=False),
        sa.Column("scheduled_count", sa.Integer(), nullable=False),
        sa.Column("debt_count", sa.Integer(), nullable=False),
        sa.Column("relaxed_by", sa.String(length=8), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "relaxed_by IN ('TIER1', 'TIER2', 'TIER3')",
            name=op.f("ck_training_debts_debt_relaxed_by_enum"),
        ),
        sa.CheckConstraint("debt_count >= 0", name=op.f("ck_training_debts_debt_count_nonneg")),
        sa.CheckConstraint(
            "required_count >= 0", name=op.f("ck_training_debts_debt_required_nonneg")
        ),
        sa.CheckConstraint(
            "scheduled_count >= 0", name=op.f("ck_training_debts_debt_scheduled_nonneg")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.plan_id"],
            name=op.f("fk_training_debts_plan_id_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("debt_id", name=op.f("pk_training_debts")),
        sa.UniqueConstraint("plan_id", "person_id", "mission_id", name="uq_training_debts_key"),
    )
    op.create_index(op.f("ix_training_debts_plan_id"), "training_debts", ["plan_id"], unique=False)
    op.create_table(
        "aircraft_mission_capability",
        sa.Column("aircraft_id", sa.String(length=8), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("mission_id", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["aircraft_id", "snapshot_id"],
            ["aircraft.aircraft_id", "aircraft.snapshot_id"],
            name=op.f("fk_aircraft_mission_capability_aircraft_id_snapshot_id_aircraft"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["mission_id", "snapshot_id"],
            ["missions.mission_id", "missions.snapshot_id"],
            name=op.f("fk_aircraft_mission_capability_mission_id_snapshot_id_missions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "aircraft_id", "snapshot_id", "mission_id", name=op.f("pk_aircraft_mission_capability")
        ),
    )
    op.create_table(
        "mission_aircraft_types",
        sa.Column("mission_id", sa.String(length=16), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("aircraft_type", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id", "snapshot_id"],
            ["missions.mission_id", "missions.snapshot_id"],
            name=op.f("fk_mission_aircraft_types_mission_id_snapshot_id_missions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "mission_id", "snapshot_id", "aircraft_type", name=op.f("pk_mission_aircraft_types")
        ),
    )
    op.create_table(
        "mission_prereq",
        sa.Column("mission_id", sa.String(length=16), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("prereq_ref", sa.String(length=16), nullable=False),
        sa.Column("ref_kind", sa.String(length=8), nullable=False),
        sa.CheckConstraint(
            "ref_kind IN ('mission', 'class')", name=op.f("ck_mission_prereq_prereq_ref_kind_enum")
        ),
        sa.CheckConstraint(
            "mission_id <> prereq_ref", name=op.f("ck_mission_prereq_prereq_no_self_loop")
        ),
        sa.ForeignKeyConstraint(
            ["mission_id", "snapshot_id"],
            ["missions.mission_id", "missions.snapshot_id"],
            name=op.f("fk_mission_prereq_mission_id_snapshot_id_missions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "mission_id", "snapshot_id", "prereq_ref", name=op.f("pk_mission_prereq")
        ),
    )
    op.create_table(
        "person_completed_missions",
        sa.Column("person_id", sa.String(length=8), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("mission_id", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id", "snapshot_id"],
            ["missions.mission_id", "missions.snapshot_id"],
            name=op.f("fk_person_completed_missions_mission_id_snapshot_id_missions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id", "snapshot_id"],
            ["persons.person_id", "persons.snapshot_id"],
            name=op.f("fk_person_completed_missions_person_id_snapshot_id_persons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "person_id", "snapshot_id", "mission_id", name=op.f("pk_person_completed_missions")
        ),
    )
    op.create_table(
        "sortie_crew",
        sa.Column("sortie_id", sa.String(length=32), nullable=False),
        sa.Column("person_id", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=8), nullable=False),
        sa.CheckConstraint(
            "role IN ('教员', '学员', '单飞', '复训')",
            name=op.f("ck_sortie_crew_sortie_crew_role_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["sortie_id"],
            ["sorties.sortie_id"],
            name=op.f("fk_sortie_crew_sortie_id_sorties"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("sortie_id", "person_id", name=op.f("pk_sortie_crew")),
        sa.UniqueConstraint("sortie_id", "role", name="uq_sortie_crew_sortie_id_role"),
    )
    op.create_table(
        "training_progress",
        sa.Column("person_id", sa.String(length=8), nullable=False),
        sa.Column("mission_id", sa.String(length=16), nullable=False),
        sa.Column("cycle_start", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("completed_count", sa.Integer(), nullable=False),
        sa.Column("last_done_date", sa.Date(), nullable=True),
        sa.Column("cycle_weeks", sa.Integer(), nullable=False),
        sa.Column("debt_count", sa.Integer(), nullable=False),
        sa.Column("prereq_met", sa.Boolean(), nullable=False),
        sa.Column("blocked_reason", sa.Text(), nullable=True),
        sa.Column("is_recurrent", sa.Boolean(), nullable=False),
        sa.Column("recurrent_since", sa.Date(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "status IN ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED')",
            name=op.f("ck_training_progress_progress_status_enum"),
        ),
        sa.CheckConstraint(
            "(is_recurrent AND recurrent_since IS NOT NULL) OR (NOT is_recurrent AND recurrent_since IS NULL)",
            name=op.f("ck_training_progress_progress_recurrent_since_consistent"),
        ),
        sa.CheckConstraint(
            "completed_count >= 0",
            name=op.f("ck_training_progress_progress_completed_count_nonneg"),
        ),
        sa.CheckConstraint(
            "cycle_weeks > 0", name=op.f("ck_training_progress_progress_cycle_weeks_positive")
        ),
        sa.CheckConstraint(
            "debt_count >= 0", name=op.f("ck_training_progress_progress_debt_count_nonneg")
        ),
        sa.ForeignKeyConstraint(
            ["mission_id", "snapshot_id"],
            ["missions.mission_id", "missions.snapshot_id"],
            name=op.f("fk_training_progress_mission_id_snapshot_id_missions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id", "snapshot_id"],
            ["persons.person_id", "persons.snapshot_id"],
            name=op.f("fk_training_progress_person_id_snapshot_id_persons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "person_id", "mission_id", "cycle_start", name=op.f("pk_training_progress")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("training_progress")
    op.drop_table("sortie_crew")
    op.drop_table("person_completed_missions")
    op.drop_table("mission_prereq")
    op.drop_table("mission_aircraft_types")
    op.drop_table("aircraft_mission_capability")
    op.drop_index(op.f("ix_training_debts_plan_id"), table_name="training_debts")
    op.drop_table("training_debts")
    op.drop_index(op.f("ix_sorties_plan_id"), table_name="sorties")
    op.drop_table("sorties")
    op.drop_table("runway_aircraft_types")
    op.drop_table("person_unavailability")
    op.drop_table("person_qualifications")
    op.drop_table("person_aircraft_types")
    op.drop_table("missions")
    op.drop_index(op.f("ix_blocked_items_plan_id"), table_name="blocked_items")
    op.drop_table("blocked_items")
    op.drop_table("aircraft_maintenance")
    op.drop_table("runways")
    op.drop_table("plans")
    op.drop_table("persons")
    op.drop_table("airspaces")
    op.drop_table("aircraft")
    op.drop_index(op.f("ix_trace_events_run_id"), table_name="trace_events")
    op.drop_table("trace_events")
    op.drop_table("semantics_versions")
    op.drop_table("rulesets")
    op.drop_index("ix_procedural_memories_lookup", table_name="procedural_memories")
    op.drop_table("procedural_memories")
    op.drop_index("ix_episodic_memories_validity", table_name="episodic_memories")
    op.drop_index(op.f("ix_episodic_memories_session_id"), table_name="episodic_memories")
    op.drop_table("episodic_memories")
    op.drop_table("data_snapshots")
    op.drop_index(op.f("ix_audit_log_ts"), table_name="audit_log")
    op.drop_index("ix_audit_log_resource", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
